# Generated by Django 5.2.8 on 2025-12-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Введите имя пользователя",
                max_length=150,
                null=True,
            ),
        ),
    ]
