# Generated by Django 5.2.9 on 2025-12-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Введите имя пользователя",
                max_length=150,
                null=True,
                unique=True,
            ),
        ),
    ]
