# Generated by Django 5.2.8 on 2025-11-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Изображение",
                null=True,
                upload_to="courses/images",
            ),
        ),
    ]
