# Generated by Django 5.2.9 on 2025-12-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
